export const categoryList = [
  {
    catlevel: 2,
    categoryid: 10000,
    ordernumber: 4,
    category_label: 'Services',
    parentcategoryid: 10011,
  },
  {
    catlevel: 3,
    categoryid: 5153,
    ordernumber: 4,
    category_label: 'Connector Cables',
    parentcategoryid: 10008,
  },
  {
    catlevel: 1,
    categoryid: 4900,
    ordernumber: 1,
    category_label: 'Accessories',
    parentcategoryid: 1,
  },
  {
    catlevel: 3,
    categoryid: 4974,
    ordernumber: 6,
    category_label: 'Mounting Kits',
    parentcategoryid: 10296,
  },
  {
    catlevel: 2,
    categoryid: 5131,
    ordernumber: 22,
    category_label: 'Carrying Cases',
    parentcategoryid: 4900,
  },
  {
    catlevel: 3,
    categoryid: 5174,
    ordernumber: 3,
    category_label: 'Digital Still Cameras',
    parentcategoryid: 10121,
  },
  {
    catlevel: 3,
    categoryid: 5089,
    ordernumber: 39,
    category_label: 'Ink/Toner Cartridges',
    parentcategoryid: 5246,
  },
  {
    catlevel: 3,
    categoryid: 10025,
    ordernumber: 7,
    category_label: 'Tablets',
    parentcategoryid: 10041,
  },
  {
    catlevel: 1,
    categoryid: 2,
    ordernumber: 23,
    category_label: 'Miscellaneous',
    parentcategoryid: 1,
  },
  {
    catlevel: 3,
    categoryid: 10264,
    ordernumber: 8,
    category_label: 'Headsets/Earsets',
    parentcategoryid: 10122,
  },
  {
    catlevel: 3,
    categoryid: 5243,
    ordernumber: 3,
    category_label: 'Mobile Phones',
    parentcategoryid: 5241,
  },
];
