export const REQUEST_START = "REQUEST_START";

export const PAGE_LOADED = "PAGE_LOADED_SUCCESSFULLF";
export const PAGE_LOAD_FAIL = "PAGE_LOADING_FAILED";

export const CATEGORY_LOADED = "CATEGORY_LOADED_SUCCESSFULLY";
export const CATEGORY_LOAD_FAIL = "CATEGORY_LOADING_FAILT";

export const PRODUCTS_LIST_LOADED = "PRODUCTS_LIST_LOADING_SUCCESSFYLLY";
export const PRODUCTS_LIST_LOAD_FAIL = "PRODUCTS_LIST_LOADING_FAIL";

export const SEARCH_RESULTS_LOADED = "SEARCH_RESULTS_LOADING_SUCCESSFYLLY";
export const SEARCH_RESULTS_LOAD_FAIL = "SEARCH_RESULTS_LOADING_FAIL";

export const PRODUCT_LOADED = "PRODUCT_LOADED_SUCCESSFULLY";
export const PRODUCT_LOAD_FAIL = "PRODUCT_LOADING_FAIL";

export const PRODUCT_BASIC_OVERVIEW_LOADED =
  "PRODUCT_BASIC_OVERVIEW_LOADED_SUCCESSFULLY";
export const PRODUCT_BASIC_OVERVIEW_LOAD_FAIL =
  "PRODUCT_BASIC_OVERVIEW_LOADING_FAIL";

export const PRODUCT_SPECIFICATIONS_LOADED =
  "PRODUCT_SPECIFICATIONS_LOADED_SUCCESSFULLY";
export const PRODUCT_SPECIFICATIONS_LOAD_FAIL =
  "PRODUCT_SPECIFICATIONS_LOADING_FAIL";

export const PRODUCT_GALLERY_LOADED = "PRODUCT_GALLERY_LOADED_SUCCESSFULLY";
export const PRODUCT_GALLERY_LOAD_FAIL = "PRODUCT_GALLERY_LOADING_FAIL";

export const PRODUCT_SIMILAR_LOADED = "PRODUCT_SIMILAR_LOADED_SUCCESSFULLY";
export const PRODUCT_SIMILAR_LOAD_FAIL = "PRODUCT_SIMILAR_LOADING_FAIL";

export const PRODUCT_ACCESSORIES_LOADED =
  "PRODUCT_ACCESSORIES_LOADED_SUCCESSFULLY";
export const PRODUCT_ACCESSORIES_LOAD_FAIL = "PRODUCT_ACCESSORIES_LOADING_FAIL";

export const CATEGORY_FILTER_LOADED = "CATEGORY_FILTER_LOADED_SUCCESSFULLY";
export const CATEGORY_FILTER_LOAD_FAIL = "CATEGORY_FILTER_LOADING_FAIL";

export const PRODUCT_TYPE_FILTER_LOADED =
  "PRODUCT_TYPE_FILTER_LOADED_SUCCESSFULLY";
export const PRODUCT_TYPE_FILTER_LOAD_FAIL = "PRODUCT_TYPE_FILTER_LOADING_FAIL";

export const MANUFACTURER_FILTER_LOADED =
  "MANUFACTURER_FILTER_LOADED_SUCCESSFULLY";
export const MANUFACTURER_FILTER_LOAD_FAIL = "MANUFACTURER_FILTER_LOADING_FAIL";
