export const PAGE_LOAD_START = "PAGE_LOAD_START";
export const PAGE_LOADED = "PAGE_LOADED_SUCCESSFULLF";
export const PAGE_LOAD_FAIL = "PAGE_LOADING_FAILED";

export const CATEGORY_LOAD_START = "CATEGORY_LOADING_START";
export const CATEGORY_LOADED = "CATEGORY_LOADED_SUCCESSFULLY";
export const CATEGORY_LOAD_FAIL = "CATEGORY_LOADING_FAILT";

export const PRODUCTS_LIST_LOAD_START = "PRODUCTS_LIST_LOADING_START";
export const PRODUCTS_LIST_LOADED = "PRODUCTS_LIST_LOADING_SUCCESSFYLLY";
export const PRODUCTS_LIST_LOAD_FAIL = "PRODUCTS_LIST_LOADING_FAIL";

export const PRODUCT_LOAD_START = "PRODUCT_LOADING_START";
export const PRODUCT_LOADED = "PRODUCT_LOADED_SUCCESSFULLY";
export const PRODUCT_LOAD_FAIL = "PRODUCT_LOADING_FAIL";

export const CATEGORY_FILTER_LOAD_START = "CATEGORY_FILTER_LOADING_START";
export const CATEGORY_FILTER_LOADED = "CATEGORY_FILTER_LOADED_SUCCESSFULLY";
export const CATEGORY_FILTER_LOAD_FAIL = "CATEGORY_FILTER_LOADING_FAIL";

export const PRODUCT_TYPE_FILTER_LOAD_START =
  "PRODUCT_TYPE_FILTER_LOADING_START";
export const PRODUCT_TYPE_FILTER_LOADED =
  "PRODUCT_TYPE_FILTER_LOADED_SUCCESSFULLY";
export const PRODUCT_TYPE_FILTER_LOAD_FAIL = "PRODUCT_TYPE_FILTER_LOADING_FAIL";

export const MANUFACTURER_FILTER_LOAD_START =
  "MANUFACTURER_FILTER_LOADING_START";
export const MANUFACTURER_FILTER_LOADED =
  "MANUFACTURER_FILTER_LOADED_SUCCESSFULLY";
export const MANUFACTURER_FILTER_LOAD_FAIL = "MANUFACTURER_FILTER_LOADING_FAIL";
